# Generated by Django 3.0 on 2019-12-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inwestycje', '0002_product_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user_id',
            new_name='user',
        ),
    ]
